scrape_configs:
  - job_name: stat_vhost
    honor_labels: true
    metrics_path: /__internal_status_vhost/format/prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: instance
    #     regex: "([^:]+)(:[0-9]+)?"
    #     replacement: "${1}"
    static_configs:
      - targets:
          - 88642bb8-e4b6-4caf-afe0-6461140fd2db.gw.mbr.massbitroute.com
          - 28829073-4715-49eb-aeef-0f6834062881.gw.mbr.massbitroute.com
          - 3a2187e4-45b8-491f-be6a-d4222ee80e72.gw.mbr.massbitroute.com
          - e577b6d6-a4b5-40b5-8f84-21b81311bc27.gw.mbr.massbitroute.com
