scrape_configs:
  - job_name: stat_vhost
    honor_labels: true
    metrics_path: /__internal_status_vhost/format/prometheus
    scrape_interval: 10s
    scrape_timeout: 5s
    # relabel_configs:
    #   - source_labels: [__address__]
    #     target_label: instance
    #     regex: "([^:]+)(:[0-9]+)?"
    #     replacement: "${1}"
    static_configs:
      - targets:
          - cba0077a-79e2-4062-b1cc-23c0a8f58725.gw.mbr.massbitroute.com
          - 8c15086e-6354-4aa7-b3ce-a829d2941288.gw.mbr.massbitroute.com
