return {
["MBR_ENV"]="dev",
["DOMAIN"]="massbitroute.dev",
["MBR_API"]="http://api.massbitroute.dev",
["WHITELIST_PARTNERS"]="allow 34.124.164.200; allow 222.253.82.171; deny all;export",
["SESSION_IV"]="123mbrbaysao4567",
["SESSION_EXPIRES"]="30dexport",
["GIT_PRIVATE_AUTH"]="massbit:c671e4ea06280e7a3f6f9aea6e8155fcde9bc703",
["PRIVATE_GIT_DOMAIN"]="git.massbitroute.dev",
["GIT_PRIVATE_DOMAIN"]="git.massbitroute.dev",
["PUBLIC_GIT_DOMAIN"]="github.com",
["GIT_PUBLIC_URL"]="https://github.com",
["GIT_PRIVATE_READ_URL"]="https://massbit:c671e4ea06280e7a3f6f9aea6e8155fcde9bc703@git.massbitroute.dev",
["GIT_AUTH_MAIL"]="",
["GIT_AUTH_NAME"]="",
["GIT_NODE_WRITE"]="",
["GIT_GATEWAY_WRITE"]="",
["GIT_GWMAN_WRITE"]="",
["GIT_STAT_WRITE"]="",
["GIT_MONITOR_WRITE"]="",
["GIT_API_WRITE"]="",
["GIT_APIDEPLOY_WRITE"]="",
["GIT_GBC_WRITE"]="",
["GIT_ASDF_WRITE"]="",
["GIT_SSL_WRITE"]="",
["GIT_MKAGENT_WRITE"]="",
["GIT_READ"]="massbit:c671e4ea06280e7a3f6f9aea6e8155fcde9bc703",
}
